[[redirects]]
  from = "/floor/1"
  to = "/floor/1"
[[redirects]]
  from = "/floor/2"
  to = "/"
  status = 200
[[redirects]]
  from = "/floor/3"
  to = "/"
  status = 200
[[redirects]]
  from = "/floor/4"
  to = "/"
  status = 200
[[redirects]]
  from = "/overview"
  to = "/"
  status = 200
